import { v4 as uuidv4 } from "uuid"
import type { Task } from "@/context/task-context"

export const mockTasks: Task[] = [
  {
    id: uuidv4(),
    name: "Interview with Design Team",
    status: "TO-DO",
    dueDate: "Today",
    category: "Work",
    priority: 2,
  },
  {
    id: uuidv4(),
    name: "Team Meeting",
    status: "TO-DO",
    dueDate: "Today",
    category: "Personal",
    priority: 2,
  },
  {
    id: uuidv4(),
    name: "Design a Dashboard page along with wireframes",
    status: "TO-DO",
    dueDate: "31 Dec, 2024",
    category: "Work",
    priority: 2,
  },
  {
    id: uuidv4(),
    name: "Morning Workout",
    status: "IN-PROGRESS",
    dueDate: "Today",
    category: "Work",
    priority: 2,
  },
  {
    id: uuidv4(),
    name: "Code Review",
    status: "TO-DO",
    dueDate: "Today",
    category: "Personal",
    priority: 2,
  },
  {
    id: uuidv4(),
    name: "Update Task Tracker",
    status: "IN-PROGRESS",
    dueDate: "25 Dec, 2024",
    category: "Work",
    priority: 2,
  },
  {
    id: uuidv4(),
    name: "Develop Login Authentication",
    status: "IN-PROGRESS",
    dueDate: "22 Dec, 2024",
    category: "Work",
    priority: 2,
  },
  {
    id: uuidv4(),
    name: "Create Marketing Campaign Plan",
    status: "IN-PROGRESS",
    dueDate: "18 Dec, 2024",
    category: "Work",
    priority: 2,
  },
  {
    id: uuidv4(),
    name: "Test API Integration",
    status: "IN-PROGRESS",
    dueDate: "12 Dec, 2024",
    category: "Work",
    priority: 2,
  },
  {
    id: uuidv4(),
    name: "Update Documentation for Release",
    status: "IN-PROGRESS",
    dueDate: "10 Dec, 2024",
    category: "Work",
    priority: 2,
  },
  {
    id: uuidv4(),
    name: "Resolve Bugs in Payment Gateway",
    status: "IN-PROGRESS",
    dueDate: "02 Dec, 2024",
    category: "Work",
    priority: 2,
  },
  {
    id: uuidv4(),
    name: "Submit Project Proposal",
    status: "COMPLETED",
    dueDate: "Today",
    category: "Work",
    priority: 2,
  },
  {
    id: uuidv4(),
    name: "Birthday Gift Shopping",
    status: "COMPLETED",
    dueDate: "Today",
    category: "Personal",
    priority: 2,
  },
  {
    id: uuidv4(),
    name: "Client Presentation",
    status: "COMPLETED",
    dueDate: "25 Dec, 2024",
    category: "Work",
    priority: 2,
  },
]

